# -*- coding: utf-8 -*-
"""Hangman game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15VuHsE_z2IiD-TaIiKN96shzGz3PMTIz
"""

!pip install rich -q

# ==========================================
# HANGMAN GAME PROJECT
# Features: Random Word Selection, Rich Panels,
# Input Validation, and Smart Hint System.
# ==========================================

import random
from rich.console import Console
from rich.panel import Panel

# Initialize the Rich console for modern styling
console = Console()

# --- GAME CONFIGURATION & VARIABLES ---
word_list = ["PYTHON", "DEVELOPER", "NOTEBOOK", "VARIABLE", "FUNCTION"]
answer_word = random.choice(word_list)
hidden_word = " ".join(["_"] * len(answer_word))

incorrect_letters = []
remaining_mistakes = 6

# Hangman art dictionary
hangman = {
    1:r'''
  +---+
  |   |
  O   |
      |
      |
      |
=========''',
    2:r'''
  +---+
  |   |
  O   |
  |   |
      |
      |
=========''',
    3:r'''
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''',
    4:r'''
  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========''',
    5:r'''
  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========''',
    6:r'''
  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
========='''
}

# Display the main title panel when the program starts
console.print(Panel(
    "[bold cyan]HANGMAN GAME[/bold cyan]\n[italic]Can you guess the hidden word before time runs out?[/italic]",
    title="🎮 WELCOME 🎮",
    border_style="cyan",
    expand=False
))

# --- MAIN GAME LOOP ---
while remaining_mistakes > 0 and hidden_word.count("_") > 0:
    print("\n==============================================")
    print(f"The hidden word is: {hidden_word}")
    print(f"Incorrect letters: {incorrect_letters}")
    print("Pick a letter (or type 'HINT' for a clue):")

    picked_letter = input().upper()

    # --- ADVANCED FEATURE: SMART HINT SYSTEM ---
    if picked_letter == "HINT":
        underscore_indices = [i for i, char in enumerate(hidden_word) if char == "_"]

        if underscore_indices:
            hint_index = random.choice(underscore_indices)
            answer_index = hint_index // 2
            hint_letter = answer_word[answer_index]

            print(f"💡 HINT: The word contains the letter '{hint_letter}'!")

            index_count = 0
            for letter in answer_word:
                if letter == hint_letter:
                    hidden_word = hidden_word[:index_count] + hint_letter + hidden_word[index_count + 1:]
                index_count += 2

            remaining_mistakes -= 1
            print(f"Using a hint cost you 1 life! Mistakes left: {remaining_mistakes}")

            if remaining_mistakes == 0:
                break
        else:
            print("No hidden letters left to hint!")
        continue

    # --- INPUT VALIDATION ---
    if not picked_letter.isalpha() or len(picked_letter) != 1:
        print("INVALID INPUT! Please enter a single letter only (no numbers or symbols).")
        continue

    # --- DUPLICATE CHECK ---
    if picked_letter in incorrect_letters or picked_letter in hidden_word.replace(" ", ""):
        print(f"You already guessed '{picked_letter}'! Try a different letter.")
        continue

    # --- GUESS EVALUATION (CORRECT) ---
    if picked_letter in answer_word:
        print(f"CORRECT! The word contains the letter {picked_letter}!")

        index_count = 0
        for letter in answer_word:
            if letter == picked_letter:
                hidden_word = hidden_word[:index_count] + picked_letter + hidden_word[index_count + 1:]
            index_count += 2

    # --- GUESS EVALUATION (INCORRECT) ---
    else:
        remaining_mistakes -= 1
        incorrect_letters.append(picked_letter)
        print(f"WRONG! Number of mistakes left: {remaining_mistakes}")

        mistakes_made = 6 - remaining_mistakes
        print(hangman[mistakes_made])

# --- END OF GAME SCREEN ---
print("\n==============================================")
if remaining_mistakes == 0:
    console.print(Panel(
        "[bold red]💀 GAME OVER 💀[/bold red]\n[red]You ran out of mistakes and were hanged.[/red]",
        title="❌ DEFEAT ❌",
        border_style="red",
        expand=False
    ))
else:
    console.print(Panel(
        "[bold green]🎉 CONGRATULATIONS! 🎉[/bold green]\n[green]You guessed the right word and survived![/green]",
        title="🏆 VICTORY 🏆",
        border_style="green",
        expand=False
    ))

print(f"The correct answer was: {answer_word}")